document.write('<!DOCTYPE html>');
document.write('<html>');
document.write('<head>');
document.write('	<meta charset="utf-8">');
document.write('	<meta http-equiv="X-UA-Compatible" content="IE=edge">');
document.write('	<meta name="viewport" content="width=device-width, initial-scale=1.0">');
document.write('');
document.write('	<title>Vaibhav Sharma</title>');
document.write('');
document.write('	<link rel="icon" href="unnamed.png" type="image/png" />');
document.write('	<!-- <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">');
document.write('	<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">');
document.write('	<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">');
document.write('	<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">');
document.write('	<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">');
document.write('	<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">');
document.write('	<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">');
document.write('	<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">');
document.write('	<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">');
document.write('	<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">');
document.write('	<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">');
document.write('	<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">');
document.write('	<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">');
document.write('	<link rel="manifest" href="/manifest.json">');
document.write('	<meta name="msapplication-TileColor" content="#ffffff">');
document.write('	<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">');
document.write('	<meta name="theme-color" content="#ffffff"> -->');
document.write('');
document.write('	<link href="https://fonts.googleapis.com/css?family=Reem+Kufi|Roboto:300" rel="stylesheet">');
document.write('	<link href="https://use.fontawesome.com/releases/v5.13.1/css/all.css" rel="stylesheet">');
document.write('	<link rel="stylesheet" href="css/reset.css">');
document.write('	<link rel="stylesheet" href="css/styles.css">');
document.write('	<link rel="stylesheet" href="css/themes/indigo-white.css">');
document.write('	<!-- <link rel="stylesheet" href="css/themes/green-white.css"> -->');
document.write('	<!-- <link rel="stylesheet" href="css/themes/red-white.css"> -->');
document.write('	<!-- <link rel="stylesheet" href="css/themes/grey-white.css"> -->');
document.write('	<!-- <link rel="stylesheet" href="css/themes/white-indigo.css"> -->');
document.write('	<!-- <link rel="stylesheet" href="css/themes/white-blue.css"> -->');
document.write('	<!-- <link rel="stylesheet" href="css/themes/white-grey.css"> -->');
document.write('	<!-- <link rel="stylesheet" href="css/themes/white-red.css"> -->');
document.write('	<!-- <link rel="stylesheet" href="css/themes/yellow-black.css"> -->');
document.write('</head>');
document.write('<body>');
document.write('	<main>');
document.write('		<p class="extreme">');
document.write('			<div class="intro">Hello, I\'m Vaibhav!</div><br>');
document.write('		</p>');
document.write('		<p class="mid">');
document.write('			<div class="typewriter"><h1>MERN | Linux | SysAdmin | FOSS Fanatic | Privacy Advocate</h1></div><br>');
document.write('		</p>');
document.write('		<!-- Find your icons from here - https://fontawesome.com/icons?d=gallery&s=brands -->');
document.write('		<div class="icons-social">');
document.write('			<a target="_blank" href="https://github.com/vaibhavsh7"><i class="fab fa-github"></i></a>');
document.write('			<a target="_blank" href="https://g.dev/vaibhav7"><i class="fab fa-google"></i></a>');
document.write('			<a target="_blank" href="https://fedoraproject.org/wiki/User:Vaibhavsharma"><i class="fab fa-fedora"></i></a>');
document.write('			<a target="_blank" href="https://www.linkedin.com/in/vaibhavsh7"><i class="fab fa-linkedin"></i></a>');
document.write('			<a target="_blank" href="mailto:vaibhavsharma74@protonmail.com"><i class="fas fa-envelope"></i></a>');
document.write('			<a target="_blank" href="https://stackoverflow.com/users/15908222/vaibhav-sharma"><i class="fab fa-stack-overflow"></i></a>');
document.write('			<a target="_blank" href="https://twitter.com/vaibhavsh74"><i class="fab fa-twitter"></i></a>');
document.write('			<a target="_blank" href="https://www.reddit.com/user/vaibhavsharma7"><i class="fab fa-reddit"></i></a>	');
document.write('    </div>');
document.write('	</main>');
document.write('</body>');
document.write('</html>');
document.write('');
